FROM anapsix/alpine-java
MAINTAINER omarcovelho
WORKDIR /
COPY ./target/word-count-app-1.0-jar-with-dependencies.jar word-count-app-1.0-jar-with-dependencies.jar
CMD ["java","-jar","/word-count-app-1.0-jar-with-dependencies.jar"]