FROM anapsix/alpine-java
MAINTAINER omarcovelho
WORKDIR /
COPY ./target/favourite-color-1.0-jar-with-dependencies.jar favourite-color-1.0-jar-with-dependencies.jar
CMD ["java","-jar","/favourite-color-1.0-jar-with-dependencies.jar"]